/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/.well-known/oauth-protected-resource": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Oauth Protected Resource Metadata */
        get: operations["oauth_protected_resource_metadata__well_known_oauth_protected_resource_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/oauth-protected-resource/mcp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Oauth Protected Resource Metadata */
        get: operations["oauth_protected_resource_metadata__well_known_oauth_protected_resource_mcp_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/api-credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Api Credentials */
        get: operations["list_api_credentials"];
        put?: never;
        /** Create Api Credential */
        post: operations["create_api_credential"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/api-credentials/{credential_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Api Credential */
        delete: operations["revoke_api_credential"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Artifact */
        get: operations["download_artifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessment-batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Assessment Batch */
        post: operations["submit_assessment_batch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessment-comparisons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compare Assessments */
        post: operations["compare_assessments"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assessments */
        get: operations["list_assessments"];
        put?: never;
        /** Submit Assessment */
        post: operations["submit_assessment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Assessment */
        get: operations["get_assessment"];
        put?: never;
        post?: never;
        /** Delete Assessment */
        delete: operations["delete_assessment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/{run_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Artifacts */
        get: operations["list_assessment_artifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Assessment */
        post: operations["cancel_assessment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/{run_id}/clean-reassessment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clean Reassess Assessment */
        post: operations["clean_reassess_assessment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/{run_id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Comments */
        get: operations["list_assessment_comments"];
        put?: never;
        /** Create Comment */
        post: operations["create_assessment_comment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/{run_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Decision */
        get: operations["get_assessment_decision"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Assessment Events */
        get: operations["list_assessment_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/{run_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evidence */
        get: operations["list_assessment_evidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/{run_id}/integrity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Assessment Integrity */
        get: operations["get_assessment_integrity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/{run_id}/llm-interactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Llm Interactions */
        get: operations["list_assessment_llm_interactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/{run_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Assessment */
        post: operations["retry_assessment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/{run_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reviews */
        get: operations["list_assessment_reviews"];
        put?: never;
        /** Create Review */
        post: operations["create_assessment_review"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/{run_id}/steps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assessment Steps */
        get: operations["list_assessment_steps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/{run_id}/validations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assessment Validations */
        get: operations["list_assessment_validations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instrument-overviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Instrument Overviews */
        get: operations["list_instrument_overviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Instrument Summary */
        get: operations["get_instrument_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/{ticker}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Instrument History */
        get: operations["get_instrument_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrity/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Integrity Summary */
        get: operations["get_integrity_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["get_current_principal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/capacity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Capacity */
        get: operations["get_system_capacity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/model-routing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Routing Policy */
        get: operations["get_model_routing_policy"];
        /** Update Model Routing Policy */
        put: operations["update_model_routing_policy"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/scheduler-policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scheduler Policy */
        get: operations["get_scheduler_policy"];
        /** Update Scheduler Policy */
        put: operations["update_scheduler_policy"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Status */
        get: operations["get_system_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/validations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Validations */
        get: operations["list_validations"];
        put?: never;
        /** Schedule Validation */
        post: operations["schedule_validation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/validations/{validation_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Validation */
        post: operations["retry_validation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Webhooks */
        get: operations["list_webhooks"];
        put?: never;
        /** Create Webhook */
        post: operations["create_webhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/{webhook_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Disable Webhook */
        delete: operations["disable_webhook"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["health_liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["health_readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiCredentialView */
        ApiCredentialView: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Expires At */
            expires_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Used At */
            last_used_at: string | null;
            /** Public Id */
            public_id: string;
            /** Revoked At */
            revoked_at: string | null;
            /** Scopes */
            scopes: string[];
        };
        /** ArtifactView */
        ArtifactView: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Media Type */
            media_type: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Sha256 */
            sha256: string;
            /** Size */
            size: number;
        };
        /** AssessmentItem */
        AssessmentItem: {
            /**
             * Analysis Date
             * Format: date
             */
            analysis_date: string;
            asset_type?: components["schemas"]["AssetType"] | null;
            /** Ticker */
            ticker: string;
        };
        /**
         * AssetType
         * @enum {string}
         */
        AssetType: "stock" | "fund" | "crypto";
        /** CapacityView */
        CapacityView: {
            /** Admission Allowed */
            admission_allowed: boolean;
            /** Admission Reasons */
            admission_reasons: string[];
            /** Admitted Or Running */
            admitted_or_running: number;
            /** Gateway Active Completions */
            gateway_active_completions: number;
            /** Gateway Model */
            gateway_model: string;
            /** Gateway Reasoning Effort */
            gateway_reasoning_effort: string;
            /** Hard Max Running Total */
            hard_max_running_total: number;
            /** Max Running Total */
            max_running_total: number;
            model_routing: components["schemas"]["ModelRoutingPolicy"];
            /** Oldest Queued Seconds */
            oldest_queued_seconds: number | null;
            /** Open Circuits */
            open_circuits: string[];
            /** Queued */
            queued: number;
        };
        /** CommentView */
        CommentView: {
            /** Author */
            author: string;
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /** ComparisonRequest */
        ComparisonRequest: {
            /** Run Ids */
            run_ids: string[];
        };
        /** ComparisonView */
        ComparisonView: {
            /** Changed Sections */
            changed_sections: {
                [key: string]: string[];
            };
            /** Ratings */
            ratings: {
                [key: string]: string | null;
            };
            /** Runs */
            runs: components["schemas"]["RunView"][];
        };
        /** CreateApiCredential */
        CreateApiCredential: {
            /** Expires At */
            expires_at?: string | null;
            /** Scopes */
            scopes: string[];
        };
        /** CreateComment */
        CreateComment: {
            /** Body */
            body: string;
        };
        /** CreateReview */
        CreateReview: {
            /** Comment */
            comment: string;
            /** Verdict */
            verdict: string;
        };
        /** CreateWebhook */
        CreateWebhook: {
            /** Endpoint */
            endpoint: string;
            /** Event Types */
            event_types: string[];
            /**
             * Secret
             * Format: password
             */
            secret: string;
        };
        /** CreatedApiCredentialView */
        CreatedApiCredentialView: {
            /** Expires At */
            expires_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Scopes */
            scopes: string[];
            /** Token */
            token: string;
        };
        /** DecisionView */
        DecisionView: {
            /** Executive Summary */
            executive_summary: string;
            /** Investment Thesis */
            investment_thesis: string;
            /** Price Target */
            price_target: string | null;
            /** Rating */
            rating: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Structured */
            structured: {
                [key: string]: unknown;
            };
            /** Time Horizon */
            time_horizon: string | null;
        };
        /**
         * Depth
         * @enum {string}
         */
        Depth: "shallow" | "medium" | "deep";
        /** EvidenceView */
        EvidenceView: {
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /**
             * Collected At
             * Format: date-time
             */
            collected_at: string;
            /** Content Hash */
            content_hash: string;
            /** Effective At */
            effective_at: string | null;
            /** Freshness */
            freshness: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Source */
            source: string;
            /** Tool Name */
            tool_name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InstrumentHistoryItem */
        InstrumentHistoryItem: {
            /** Config Snapshot Sha256 */
            config_snapshot_sha256: string | null;
            /** Executive Summary */
            executive_summary: string | null;
            /** Gateway Fast Model */
            gateway_fast_model?: string | null;
            /** Gateway Fast Reasoning Effort */
            gateway_fast_reasoning_effort?: string | null;
            /** Gateway Model */
            gateway_model: string | null;
            /** Gateway Reasoning Effort */
            gateway_reasoning_effort: string | null;
            /** Gateway Slow Model */
            gateway_slow_model?: string | null;
            /** Gateway Slow Reasoning Effort */
            gateway_slow_reasoning_effort?: string | null;
            /**
             * Is Latest Attempt
             * @default true
             */
            is_latest_attempt: boolean;
            /**
             * Memory Mode
             * @default independent
             */
            memory_mode: string;
            /**
             * Memory Source Count
             * @default 0
             */
            memory_source_count: number;
            /** Price Target */
            price_target: string | null;
            /** Rating */
            rating: string | null;
            /**
             * Request Attempt Count
             * @default 1
             */
            request_attempt_count: number;
            run: components["schemas"]["RunView"];
            /** Validation Outcome */
            validation_outcome?: string | null;
            /** Validations */
            validations?: components["schemas"]["InstrumentValidationView"][];
        };
        /** InstrumentIdentityView */
        InstrumentIdentityView: {
            /** Asset Type */
            asset_type: string;
            /** Exchange */
            exchange: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string | null;
            /** Ticker */
            ticker: string;
        };
        /** InstrumentOverviewItem */
        InstrumentOverviewItem: {
            instrument: components["schemas"]["InstrumentIdentityView"];
            latest_decision: components["schemas"]["DecisionView"] | null;
            latest_run: components["schemas"]["RunView"];
            latest_successful_run: components["schemas"]["RunView"] | null;
            preferred_validation: components["schemas"]["InstrumentValidationView"] | null;
            /** Previous Rating */
            previous_rating: string | null;
            run_counts: components["schemas"]["InstrumentRunCounts"];
            /** Validation Stats */
            validation_stats: components["schemas"]["InstrumentValidationStats"][];
        };
        /** InstrumentOverviewPage */
        InstrumentOverviewPage: {
            /** Instrument Count */
            instrument_count: number;
            /** Items */
            items: components["schemas"]["InstrumentOverviewItem"][];
            /** Next Cursor */
            next_cursor?: string | null;
            run_counts: components["schemas"]["InstrumentRunCounts"];
            /**
             * Validations Visible
             * @default true
             */
            validations_visible: boolean;
        };
        /** InstrumentRunCounts */
        InstrumentRunCounts: {
            /**
             * Active
             * @default 0
             */
            active: number;
            /**
             * Anomalous
             * @default 0
             */
            anomalous: number;
            /**
             * Queued
             * @default 0
             */
            queued: number;
            /**
             * Succeeded
             * @default 0
             */
            succeeded: number;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /** InstrumentSummaryView */
        InstrumentSummaryView: {
            /** Assessment Count */
            assessment_count: number;
            /** Asset Types */
            asset_types: string[];
            /** Latest Created At */
            latest_created_at: string | null;
            /** Latest Rating */
            latest_rating: string | null;
            /** Latest Run Id */
            latest_run_id: string | null;
            /** Ticker */
            ticker: string;
        };
        /** InstrumentValidationStats */
        InstrumentValidationStats: {
            /** Accuracy */
            accuracy: string | null;
            /** Completed */
            completed: number;
            /** Direction Correct */
            direction_correct: number;
            /** Direction Observed */
            direction_observed: number;
            /**
             * Excluded At Risk
             * @default 0
             */
            excluded_at_risk: number;
            /**
             * Excluded Unknown
             * @default 0
             */
            excluded_unknown: number;
            /** Horizon */
            horizon: number;
        };
        /** InstrumentValidationView */
        InstrumentValidationView: {
            /** Direction Correct */
            direction_correct: boolean | null;
            /** Error Code */
            error_code: string | null;
            /** Exit Session */
            exit_session: string | null;
            /** Horizon */
            horizon: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Matures At */
            matures_at: string | null;
            /** Price Target Hit */
            price_target_hit: boolean | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Scheduled For
             * Format: date-time
             */
            scheduled_for: string;
            /** Status */
            status: string;
            /** Total Alpha */
            total_alpha: string | null;
            /** Total Return */
            total_return: string | null;
        };
        /** IntegrityFindingView */
        IntegrityFindingView: {
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Reason Code */
            reason_code: string;
            /**
             * Status
             * @enum {string}
             */
            status: "safe" | "at_risk" | "unknown";
            /** Tool Name */
            tool_name: string;
        };
        /** IntegritySummaryView */
        IntegritySummaryView: {
            /** At Risk */
            at_risk: number;
            /** Eligible Count */
            eligible_count: number;
            /** Excluded At Risk Count */
            excluded_at_risk_count: number;
            /** Excluded Unknown Count */
            excluded_unknown_count: number;
            /**
             * Policy Version
             * @default point-in-time.v1
             */
            policy_version: string;
            /** Safe */
            safe: number;
            /** Total */
            total: number;
            /** Unassessed */
            unassessed: number;
            /** Unknown */
            unknown: number;
        };
        /** IntegrityView */
        IntegrityView: {
            /**
             * Analysis Date
             * Format: date
             */
            analysis_date: string;
            /** Audit Mode */
            audit_mode?: ("live" | "retrospective") | null;
            /** Checked At */
            checked_at?: string | null;
            /** Clean Reassessment Of Run Id */
            clean_reassessment_of_run_id?: string | null;
            /** Clean Reassessment Run Id */
            clean_reassessment_run_id?: string | null;
            /**
             * Findings
             * @default []
             */
            findings: components["schemas"]["IntegrityFindingView"][];
            /** Input Fingerprint */
            input_fingerprint?: string | null;
            /**
             * Policy Version
             * @default point-in-time.v1
             */
            policy_version: string;
            /**
             * Reason Codes
             * @default []
             */
            reason_codes: string[];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "safe" | "at_risk" | "unknown" | "unassessed";
            /** Temporal Scope */
            temporal_scope?: ("contemporaneous" | "historical_reconstruction") | null;
        };
        /** LlmInteractionPage */
        LlmInteractionPage: {
            /** Complete */
            complete: boolean;
            /** Items */
            items: components["schemas"]["LlmInteractionView"][];
            /**
             * Source
             * @enum {string}
             */
            source: "live" | "sealed" | "none";
        };
        /** LlmInteractionView */
        LlmInteractionView: {
            /** Completed At */
            completed_at: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Error Code */
            error_code: string | null;
            /** Model Alias */
            model_alias: string | null;
            /** Physical Model */
            physical_model: string | null;
            /** Reasoning Effort */
            reasoning_effort: string | null;
            /** Route */
            route: string | null;
            /** Sequence */
            sequence: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Status */
            status: string;
        };
        /**
         * MemoryMode
         * @enum {string}
         */
        MemoryMode: "independent" | "historical";
        /** MemorySourceView */
        MemorySourceView: {
            /** Alpha */
            alpha: string;
            /**
             * Analysis Date
             * Format: date
             */
            analysis_date: string;
            /** Content Sha256 */
            content_sha256: string;
            /** Direction Correct */
            direction_correct?: boolean | null;
            /**
             * Exit Session
             * Format: date
             */
            exit_session: string;
            /** Horizon */
            horizon: number;
            /** Price Target Hit */
            price_target_hit?: boolean | null;
            /** Rating */
            rating: string;
            /** Raw Return */
            raw_return: string;
            /**
             * Source Run Id
             * Format: uuid
             */
            source_run_id: string;
            /**
             * Validation Id
             * Format: uuid
             */
            validation_id: string;
        };
        /** ModelRoute */
        ModelRoute: {
            /**
             * Model
             * @enum {string}
             */
            model: "gpt-5.6-terra" | "gpt-5.6-sol";
            /**
             * Reasoning Effort
             * @enum {string}
             */
            reasoning_effort: "low" | "medium" | "high" | "xhigh" | "max" | "ultra";
        };
        /** ModelRoutingPolicy */
        ModelRoutingPolicy: {
            /**
             * @default {
             *       "model": "gpt-5.6-terra",
             *       "reasoning_effort": "high"
             *     }
             */
            fast: components["schemas"]["ModelRoute"];
            /**
             * @default {
             *       "model": "gpt-5.6-sol",
             *       "reasoning_effort": "high"
             *     }
             */
            slow: components["schemas"]["ModelRoute"];
        };
        /** ModelRoutingPolicyCommand */
        ModelRoutingPolicyCommand: {
            fast: components["schemas"]["ModelRoute"];
            slow: components["schemas"]["ModelRoute"];
        };
        /** ModelRoutingPolicyView */
        ModelRoutingPolicyView: {
            /** Available Models */
            available_models: string[];
            /** Available Reasoning Efforts */
            available_reasoning_efforts: string[];
            fast: components["schemas"]["ModelRoute"];
            /** Routing Snapshot Id */
            routing_snapshot_id: string;
            slow: components["schemas"]["ModelRoute"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /** ReviewView */
        ReviewView: {
            /** Comment */
            comment: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reviewer */
            reviewer: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Verdict */
            verdict: string;
        };
        /** RunDetailView */
        RunDetailView: {
            /**
             * Analysis Date
             * Format: date
             */
            analysis_date: string;
            /** Asset Type */
            asset_type: string;
            /** Attempt */
            attempt: number;
            /** Config Snapshot Sha256 */
            config_snapshot_sha256?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Data Vendors */
            data_vendors?: {
                [key: string]: string;
            };
            /** Exchange */
            exchange?: string | null;
            /** Gateway Fast Model */
            gateway_fast_model?: string | null;
            /** Gateway Fast Reasoning Effort */
            gateway_fast_reasoning_effort?: string | null;
            /** Gateway Model */
            gateway_model?: string | null;
            /** Gateway Reasoning Effort */
            gateway_reasoning_effort?: string | null;
            /** Gateway Slow Model */
            gateway_slow_model?: string | null;
            /** Gateway Slow Reasoning Effort */
            gateway_slow_reasoning_effort?: string | null;
            /** Gateway Snapshot Id */
            gateway_snapshot_id?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Instrument Name */
            instrument_name?: string | null;
            memory?: components["schemas"]["RunMemoryView"];
            /** Model Routing Snapshot Id */
            model_routing_snapshot_id?: string | null;
            /** Prompt Schema Version */
            prompt_schema_version?: string | null;
            /** Request Config */
            request_config?: {
                [key: string]: unknown;
            };
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /** Resolved Config */
            resolved_config?: {
                [key: string]: unknown;
            };
            /** Root Commit */
            root_commit?: string | null;
            status: components["schemas"]["RunStatus"];
            /** Ticker */
            ticker: string;
            /** Tool Vendors */
            tool_vendors?: {
                [key: string]: string;
            };
            /** Tradingagents Commit */
            tradingagents_commit?: string | null;
        };
        /** RunMemoryView */
        RunMemoryView: {
            /** @default independent */
            mode: components["schemas"]["MemoryMode"];
            /** Snapshot Sha256 */
            snapshot_sha256?: string | null;
            /**
             * Sources
             * @default []
             */
            sources: components["schemas"]["MemorySourceView"][];
        };
        /** RunPage */
        RunPage: {
            /** Items */
            items: components["schemas"]["RunView"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "queued" | "admitted" | "starting" | "running_analysts" | "research_debate" | "trader_plan" | "risk_debate" | "portfolio_decision" | "finalizing" | "succeeded" | "failed" | "cancel_requested" | "cancelling" | "cancelled" | "needs_attention";
        /** RunStepView */
        RunStepView: {
            /** Attempt */
            attempt: number;
            /** Error Code */
            error_code: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Name */
            name: string;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
            /** Summary */
            summary: string | null;
        };
        /** RunView */
        RunView: {
            /**
             * Analysis Date
             * Format: date
             */
            analysis_date: string;
            /** Asset Type */
            asset_type: string;
            /** Attempt */
            attempt: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Exchange */
            exchange?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Instrument Name */
            instrument_name?: string | null;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            status: components["schemas"]["RunStatus"];
            /** Ticker */
            ticker: string;
        };
        /** ScheduleValidation */
        ScheduleValidation: {
            /** Horizons */
            horizons?: (1 | 5 | 20)[] | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /** SchedulerPolicyCommand */
        SchedulerPolicyCommand: {
            /** Cpu Limit Percent */
            cpu_limit_percent: number;
            /** Gateway Active Limit */
            gateway_active_limit: number;
            /**
             * Hard Max Running Total
             * @default 32
             */
            hard_max_running_total: number;
            /** Max Running Total */
            max_running_total: number;
            /** Minimum Disk Gib */
            minimum_disk_gib: number;
            /** Minimum Disk Percent */
            minimum_disk_percent: number;
            /** Minimum Memory Gib */
            minimum_memory_gib: number;
        };
        /** SchedulerPolicyView */
        SchedulerPolicyView: {
            /** Cpu Limit Percent */
            cpu_limit_percent: number;
            /** Gateway Active Limit */
            gateway_active_limit: number;
            /**
             * Hard Max Running Total
             * @default 32
             */
            hard_max_running_total: number;
            /** Max Running Total */
            max_running_total: number;
            /** Minimum Disk Gib */
            minimum_disk_gib: number;
            /** Minimum Disk Percent */
            minimum_disk_percent: number;
            /** Minimum Memory Gib */
            minimum_memory_gib: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /** SubmitAssessments */
        SubmitAssessments: {
            /**
             * Analysts
             * @default [
             *       "market",
             *       "social",
             *       "news",
             *       "fundamentals"
             *     ]
             */
            analysts: string[];
            /** @default deep */
            depth: components["schemas"]["Depth"];
            /** Idempotency Key */
            idempotency_key: string;
            /** Items */
            items: components["schemas"]["AssessmentItem"][];
            /**
             * Language
             * @default Chinese
             */
            language: string;
            /** @default independent */
            memory_mode: components["schemas"]["MemoryMode"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationTriggerResults */
        ValidationTriggerResults: {
            /** Data Quality Status */
            data_quality_status?: ("matched" | "minor_difference" | "material_difference" | "not_available") | null;
            /** Direction */
            direction?: ("bullish" | "bearish" | "neutral") | null;
            /** Direction Basis */
            direction_basis?: ("instrument_total_return" | "benchmark_total_alpha") | null;
            /** Direction Correct */
            direction_correct?: boolean | null;
            /** Direction Rule Version */
            direction_rule_version?: "rating-direction.v2" | null;
            /** Entry Price */
            entry_price?: string | null;
            /** Entry Session */
            entry_session?: string | null;
            /** Exit Price */
            exit_price?: string | null;
            /** Exit Session */
            exit_session?: string | null;
            /** Price Target Hit */
            price_target_hit?: boolean | null;
            /** Price Target Status */
            price_target_status?: ("not_set" | "basis_pending" | "basis_unavailable" | "evaluated") | null;
            /** Rating */
            rating?: string | null;
            /** Rebased Price Target */
            rebased_price_target?: string | null;
        };
        /** ValidationView */
        ValidationView: {
            /** Alpha */
            alpha: string | null;
            /** Benchmark Price Return */
            benchmark_price_return?: string | null;
            /** Benchmark Return */
            benchmark_return: string | null;
            /** Benchmark Total Return */
            benchmark_total_return?: string | null;
            /**
             * Calculation Version
             * @default validation.v1
             * @enum {string}
             */
            calculation_version: "validation.v1" | "validation.v2";
            /** Calendar Code */
            calendar_code?: string | null;
            /** Data Artifact Id */
            data_artifact_id?: string | null;
            /** Entry Session */
            entry_session?: string | null;
            /** Error Code */
            error_code?: string | null;
            /** Exit Session */
            exit_session?: string | null;
            /**
             * Horizon
             * @enum {integer}
             */
            horizon: 1 | 5 | 20;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Matures At */
            matures_at?: string | null;
            /** Max Adverse Excursion */
            max_adverse_excursion: string | null;
            /** Max Favorable Excursion */
            max_favorable_excursion: string | null;
            /** Normalization Version */
            normalization_version?: string | null;
            /** Observed At */
            observed_at: string | null;
            /** Price Alpha */
            price_alpha?: string | null;
            /** Price Return */
            price_return?: string | null;
            /** Provider Adapter Version */
            provider_adapter_version?: string | null;
            /** Provider Id */
            provider_id?: string | null;
            /** Raw Return */
            raw_return: string | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Scheduled For
             * Format: date-time
             */
            scheduled_for: string;
            /**
             * Status
             * @enum {string}
             */
            status: "scheduled" | "running" | "completed" | "retry_wait" | "unavailable" | "failed";
            /** Total Alpha */
            total_alpha?: string | null;
            /** Total Return */
            total_return?: string | null;
            trigger_results?: components["schemas"]["ValidationTriggerResults"];
        };
        /** WebhookView */
        WebhookView: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Endpoint */
            endpoint: string;
            /** Event Types */
            event_types: string[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    oauth_protected_resource_metadata__well_known_oauth_protected_resource_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    oauth_protected_resource_metadata__well_known_oauth_protected_resource_mcp_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_api_credentials: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiCredentialView"][];
                };
            };
        };
    };
    create_api_credential: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApiCredential"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedApiCredentialView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_api_credential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                credential_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_artifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_assessment_batch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitAssessments"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_assessments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComparisonRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assessments: {
        parameters: {
            query?: {
                ticker?: string | null;
                status?: components["schemas"]["RunStatus"][] | null;
                submitted_by?: string | null;
                created_from?: string | null;
                created_to?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_assessment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitAssessments"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_assessment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_assessment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assessment_artifacts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_assessment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clean_reassess_assessment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assessment_comments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_assessment_comment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateComment"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_assessment_decision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assessment_events: {
        parameters: {
            query?: {
                after?: number;
                limit?: number;
            };
            header?: {
                accept?: string | null;
                "Last-Event-ID"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assessment_evidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_assessment_integrity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrityView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assessment_llm_interactions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmInteractionPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_assessment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assessment_reviews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_assessment_review: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReview"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assessment_steps: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStepView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assessment_validations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_instrument_overviews: {
        parameters: {
            query?: {
                query?: string | null;
                asset_type?: components["schemas"]["AssetType"] | null;
                status?: components["schemas"]["RunStatus"][] | null;
                anomalous_only?: boolean;
                created_from?: string | null;
                created_to?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentOverviewPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_instrument_summary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentSummaryView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_instrument_history: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentHistoryItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_integrity_summary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegritySummaryView"];
                };
            };
        };
    };
    get_current_principal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_system_capacity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapacityView"];
                };
            };
        };
    };
    get_model_routing_policy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelRoutingPolicyView"];
                };
            };
        };
    };
    update_model_routing_policy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelRoutingPolicyCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelRoutingPolicyView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scheduler_policy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulerPolicyView"];
                };
            };
        };
    };
    update_scheduler_policy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SchedulerPolicyCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulerPolicyView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_system_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_validations: {
        parameters: {
            query?: {
                status?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    schedule_validation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleValidation"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_validation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                validation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_webhooks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookView"][];
                };
            };
        };
    };
    create_webhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWebhook"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disable_webhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health_readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
