"""initial platform schema

Revision ID: 20260725_0001
Revises:
Create Date: 2026-07-25 13:46:02.386317
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql, postgresql
from sqlalchemy.types import TypeEngine

# revision identifiers, used by Alembic.
revision: str = "20260725_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def json_type() -> TypeEngine:
    return sa.JSON().with_variant(postgresql.JSONB(), "postgresql")


def datetime_type() -> TypeEngine:
    return sa.DateTime(timezone=True).with_variant(mysql.DATETIME(fsp=6), "mysql")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("actor_type", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("object_type", sa.String(length=64), nullable=False),
        sa.Column("object_id", sa.String(length=64), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("metadata_json", json_type(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", datetime_type(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(op.f("ix_audit_events_actor_id"), "audit_events", ["actor_id"], unique=False)
    op.create_index(op.f("ix_audit_events_object_id"), "audit_events", ["object_id"], unique=False)
    op.create_index(
        op.f("ix_audit_events_request_id"), "audit_events", ["request_id"], unique=False
    )
    op.create_table(
        "instruments",
        sa.Column("canonical_ticker", sa.String(length=32), nullable=False),
        sa.Column("asset_type", sa.String(length=32), nullable=False),
        sa.Column("exchange", sa.String(length=64), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("metadata_json", json_type(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", datetime_type(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instruments")),
        sa.UniqueConstraint(
            "canonical_ticker", "asset_type", name=op.f("uq_instruments_canonical_ticker")
        ),
    )
    op.create_index(
        op.f("ix_instruments_canonical_ticker"), "instruments", ["canonical_ticker"], unique=False
    )
    op.create_table(
        "roles",
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("name", name=op.f("uq_roles_name")),
    )
    op.create_table(
        "run_config_snapshots",
        sa.Column("content_json", json_type(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("gateway_snapshot_id", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", datetime_type(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_config_snapshots")),
        sa.UniqueConstraint("sha256", name=op.f("uq_run_config_snapshots_sha256")),
    )
    op.create_table(
        "users",
        sa.Column("issuer", sa.String(length=512), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", datetime_type(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("issuer", "subject", name=op.f("uq_users_issuer")),
    )
    op.create_table(
        "api_credentials",
        sa.Column("principal_id", sa.Uuid(), nullable=False),
        sa.Column("public_id", sa.String(length=32), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("scopes_json", json_type(), nullable=False),
        sa.Column("expires_at", datetime_type(), nullable=True),
        sa.Column("last_used_at", datetime_type(), nullable=True),
        sa.Column("revoked_at", datetime_type(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", datetime_type(), nullable=False),
        sa.ForeignKeyConstraint(
            ["principal_id"], ["users.id"], name=op.f("fk_api_credentials_principal_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_credentials")),
        sa.UniqueConstraint("public_id", name=op.f("uq_api_credentials_public_id")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_api_credentials_token_hash")),
    )
    op.create_index(
        op.f("ix_api_credentials_principal_id"), "api_credentials", ["principal_id"], unique=False
    )
    op.create_table(
        "assessment_batches",
        sa.Column("submitted_by", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("defaults_json", json_type(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", datetime_type(), nullable=False),
        sa.ForeignKeyConstraint(
            ["submitted_by"], ["users.id"], name=op.f("fk_assessment_batches_submitted_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessment_batches")),
        sa.UniqueConstraint(
            "submitted_by", "idempotency_key", name=op.f("uq_assessment_batches_submitted_by")
        ),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_user_roles_role_id_roles")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_roles_user_id_users")
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id", name=op.f("pk_user_roles")),
    )
    op.create_table(
        "assessment_requests",
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_date", sa.Date(), nullable=False),
        sa.Column("requested_config_json", json_type(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", datetime_type(), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["assessment_batches.id"],
            name=op.f("fk_assessment_requests_batch_id_assessment_batches"),
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_assessment_requests_instrument_id_instruments"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessment_requests")),
    )
    op.create_table(
        "assessment_runs",
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("config_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("retry_of_run_id", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("admitted_at", datetime_type(), nullable=True),
        sa.Column("started_at", datetime_type(), nullable=True),
        sa.Column("finished_at", datetime_type(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", datetime_type(), nullable=False),
        sa.ForeignKeyConstraint(
            ["config_snapshot_id"],
            ["run_config_snapshots.id"],
            name=op.f("fk_assessment_runs_config_snapshot_id_run_config_snapshots"),
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["assessment_requests.id"],
            name=op.f("fk_assessment_runs_request_id_assessment_requests"),
        ),
        sa.ForeignKeyConstraint(
            ["retry_of_run_id"],
            ["assessment_runs.id"],
            name=op.f("fk_assessment_runs_retry_of_run_id_assessment_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessment_runs")),
    )
    op.create_index(op.f("ix_assessment_runs_status"), "assessment_runs", ["status"], unique=False)
    op.create_table(
        "artifacts",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("media_type", sa.String(length=128), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("redacted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", datetime_type(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["assessment_runs.id"], name=op.f("fk_artifacts_run_id_assessment_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifacts")),
        sa.UniqueConstraint("run_id", "kind", "sha256", name=op.f("uq_artifacts_run_id")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_artifacts_storage_key")),
    )
    op.create_index(op.f("ix_artifacts_run_id"), "artifacts", ["run_id"], unique=False)
    op.create_index(op.f("ix_artifacts_sha256"), "artifacts", ["sha256"], unique=False)
    op.create_table(
        "run_events",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("payload_json", json_type(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", datetime_type(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["assessment_runs.id"], name=op.f("fk_run_events_run_id_assessment_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_events")),
        sa.UniqueConstraint("run_id", "sequence", name=op.f("uq_run_events_run_id")),
    )
    op.create_index(op.f("ix_run_events_run_id"), "run_events", ["run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_run_events_run_id"), table_name="run_events")
    op.drop_table("run_events")
    op.drop_index(op.f("ix_artifacts_sha256"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_run_id"), table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_index(op.f("ix_assessment_runs_status"), table_name="assessment_runs")
    op.drop_table("assessment_runs")
    op.drop_table("assessment_requests")
    op.drop_table("user_roles")
    op.drop_table("assessment_batches")
    op.drop_index(op.f("ix_api_credentials_principal_id"), table_name="api_credentials")
    op.drop_table("api_credentials")
    op.drop_table("users")
    op.drop_table("run_config_snapshots")
    op.drop_table("roles")
    op.drop_index(op.f("ix_instruments_canonical_ticker"), table_name="instruments")
    op.drop_table("instruments")
    op.drop_index(op.f("ix_audit_events_request_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_object_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_actor_id"), table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
