"""execution and evidence schema

Revision ID: 20260725_0002
Revises: 20260725_0001
Create Date: 2026-07-25 14:01:46.183459
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql, postgresql
from sqlalchemy.types import TypeEngine

# revision identifiers, used by Alembic.
revision: str = "20260725_0002"
down_revision: str | None = "20260725_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def json_type() -> TypeEngine:
    return sa.JSON().with_variant(postgresql.JSONB(), "postgresql")


def datetime_type() -> TypeEngine:
    return sa.DateTime(timezone=True).with_variant(mysql.DATETIME(fsp=6), "mysql")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "circuit_breakers",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("opened_until", datetime_type(), nullable=True),
        sa.Column("backoff_seconds", sa.Integer(), nullable=False),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", datetime_type(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_circuit_breakers")),
        sa.UniqueConstraint("name", name=op.f("uq_circuit_breakers_name")),
    )
    op.create_table(
        "gateway_health_samples",
        sa.Column("sampled_at", datetime_type(), nullable=False),
        sa.Column("healthy", sa.Boolean(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("detail_json", json_type(), nullable=False),
        sa.Column("active_completions", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("reasoning_effort", sa.String(length=32), nullable=True),
        sa.Column("snapshot_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gateway_health_samples")),
    )
    op.create_index(
        op.f("ix_gateway_health_samples_sampled_at"),
        "gateway_health_samples",
        ["sampled_at"],
        unique=False,
    )
    op.create_table(
        "vendor_health_samples",
        sa.Column("sampled_at", datetime_type(), nullable=False),
        sa.Column("healthy", sa.Boolean(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("detail_json", json_type(), nullable=False),
        sa.Column("vendor", sa.String(length=128), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_health_samples")),
    )
    op.create_index(
        op.f("ix_vendor_health_samples_sampled_at"),
        "vendor_health_samples",
        ["sampled_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vendor_health_samples_vendor"), "vendor_health_samples", ["vendor"], unique=False
    )
    op.create_table(
        "workers",
        sa.Column("instance_name", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("capabilities_json", json_type(), nullable=False),
        sa.Column("pid", sa.Integer(), nullable=False),
        sa.Column("heartbeat_at", datetime_type(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", datetime_type(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workers")),
        sa.UniqueConstraint("instance_name", name=op.f("uq_workers_instance_name")),
    )
    op.create_table(
        "scheduler_policy",
        sa.Column("key", sa.String(length=32), nullable=False),
        sa.Column("content_json", json_type(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("updated_at", datetime_type(), nullable=False),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["users.id"], name=op.f("fk_scheduler_policy_updated_by_users")
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_scheduler_policy")),
    )
    op.create_table(
        "decisions",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("rating", sa.String(length=32), nullable=False),
        sa.Column("executive_summary", sa.Text(), nullable=False),
        sa.Column("investment_thesis", sa.Text(), nullable=False),
        sa.Column("price_target", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("time_horizon", sa.String(length=128), nullable=True),
        sa.Column("structured_json", json_type(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", datetime_type(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["assessment_runs.id"], name=op.f("fk_decisions_run_id_assessment_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decisions")),
        sa.UniqueConstraint("run_id", name=op.f("uq_decisions_run_id")),
    )
    op.create_table(
        "run_steps",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("started_at", datetime_type(), nullable=True),
        sa.Column("finished_at", datetime_type(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", datetime_type(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["assessment_runs.id"], name=op.f("fk_run_steps_run_id_assessment_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_steps")),
        sa.UniqueConstraint("run_id", "name", "attempt", name=op.f("uq_run_steps_run_id")),
    )
    op.create_index(op.f("ix_run_steps_run_id"), "run_steps", ["run_id"], unique=False)
    op.create_table(
        "worker_leases",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("worker_id", sa.Uuid(), nullable=False),
        sa.Column("child_pid", sa.Integer(), nullable=True),
        sa.Column("child_pgid", sa.Integer(), nullable=True),
        sa.Column("lease_expires_at", datetime_type(), nullable=False),
        sa.Column("heartbeat_at", datetime_type(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", datetime_type(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["assessment_runs.id"], name=op.f("fk_worker_leases_run_id_assessment_runs")
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"], ["workers.id"], name=op.f("fk_worker_leases_worker_id_workers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_worker_leases")),
        sa.UniqueConstraint("run_id", name=op.f("uq_worker_leases_run_id")),
    )
    op.create_index(
        op.f("ix_worker_leases_lease_expires_at"),
        "worker_leases",
        ["lease_expires_at"],
        unique=False,
    )
    op.create_table(
        "evidence_items",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("tool_name", sa.String(length=128), nullable=False),
        sa.Column("arguments_json", json_type(), nullable=False),
        sa.Column("collected_at", datetime_type(), nullable=False),
        sa.Column("effective_at", datetime_type(), nullable=True),
        sa.Column("freshness", sa.String(length=64), nullable=True),
        sa.Column("artifact_id", sa.Uuid(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", datetime_type(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artifact_id"], ["artifacts.id"], name=op.f("fk_evidence_items_artifact_id_artifacts")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["assessment_runs.id"],
            name=op.f("fk_evidence_items_run_id_assessment_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_items")),
    )
    op.create_index(
        op.f("ix_evidence_items_content_hash"), "evidence_items", ["content_hash"], unique=False
    )
    op.create_index(op.f("ix_evidence_items_run_id"), "evidence_items", ["run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_evidence_items_run_id"), table_name="evidence_items")
    op.drop_index(op.f("ix_evidence_items_content_hash"), table_name="evidence_items")
    op.drop_table("evidence_items")
    op.drop_index(op.f("ix_worker_leases_lease_expires_at"), table_name="worker_leases")
    op.drop_table("worker_leases")
    op.drop_index(op.f("ix_run_steps_run_id"), table_name="run_steps")
    op.drop_table("run_steps")
    op.drop_table("decisions")
    op.drop_table("scheduler_policy")
    op.drop_table("workers")
    op.drop_index(op.f("ix_vendor_health_samples_vendor"), table_name="vendor_health_samples")
    op.drop_index(op.f("ix_vendor_health_samples_sampled_at"), table_name="vendor_health_samples")
    op.drop_table("vendor_health_samples")
    op.drop_index(op.f("ix_gateway_health_samples_sampled_at"), table_name="gateway_health_samples")
    op.drop_table("gateway_health_samples")
    op.drop_table("circuit_breakers")
    # ### end Alembic commands ###
